ci

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -26,18 +26,18 @@ check-infra:
     - echo "Checking for infrastructure state..."
     - cd $ENV_DIR
     - terraform refresh -var-file="dev_s.tfvars" -input=$TF_INPUT || echo "Refresh failed"
+    - terraform plan -var-file="dev_s.tfvars" -input=$TF_INPUT -detailed-exitcode
+    - EXIT_CODE=$?
     - |
-      if [ -f "terraform.tfstate" ]; then
-        RESOURCE_COUNT=$(terraform state list 2>/dev/null | wc -l)
-        echo "Resource count: $RESOURCE_COUNT"
-        if [ "$RESOURCE_COUNT" -gt 0 ]; then
-          echo "Infrastructure exists. Skipping apply."
+      if [ "$EXIT_CODE" -eq 0 ]; then
+        echo "infrastructure present. skip apply"
           touch infra_exists.flag
-        else
-          echo "No infrastructure found. Proceeding to create."
-        fi
+      elif ["$EXIT_CODE" -eq 2]; then
+          echo "not up to date with the folder. Proceeding to create."
+        
       else
-        echo "No terraform.tfstate found. Proceeding to create."
+        echo "No terraform.tfstate found. plan failed."
+        exit 1
       fi
   artifacts:
     paths:
