ci

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -27,18 +27,17 @@ check-infra:
     - cd $ENV_DIR
     - terraform refresh -var-file="dev_s.tfvars" -input=$TF_INPUT || echo "Refresh failed"
     - |
-      if [ -f "terraform.tfstate" ]; then
-        RESOURCE_COUNT=$(terraform state list 2>/dev/null | wc -l)
-        echo "Resource count: $RESOURCE_COUNT"
-        ACTUAL_COUNT=$(terraform plan -var-file="dev_s.tfvars" -input=$TF_INPUT 2>/dev/null | wc -l)
-        if [ "$RESOURCE_COUNT" -eq "$ACTUAL_COUNT" ]; then
-          echo "Infrastructure exists. Skipping apply."
-          touch infra_exists.flag
-        else
-          echo "No infrastructure found/mismatch. Proceeding to create."
-        fi
+      terraform plan -detailed-exitcode -var-file="dev_s.tfvars" -input=$TF_INPUT -out=tfplan
+      $EXIT_CODE=$? 
+      if [ -f "EXIT_CODE" -eq 0 ]; then
+        echo "no changes required.skipping apply"
+        touch infra_exists.flag
+      elif ["$EXIT_CODE" -eq 2]; then
+          echo "mismatch. Proceeding to create."
+        
       else
-        echo "No terraform.tfstate found. Proceeding to create."
+        echo "No terraform.tfstate found. error."
+        exit 1
       fi
   
   artifacts:
