ff

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -16,12 +16,18 @@ check-infra:
   stage: check-infra
   script:
     - echo "Checking for infrastructure state..."
+    - terraform refresh -input=false || echo "refresh failed"
     - |
       if [ -f "environments/$ENV_DIR/terraform.tfstate" ]; then
+        RESOURCE_COUNT=$(terraform state list 2>/dev/null | wc -l)
+        if [ "$RESOURCE_COUNT" -gt 0 ]; then
         echo "Infrastructure already exists. Skipping apply."
         touch infra_exists.flag
       else
         echo "no infrastructure found . proceed to create"
+      fi
+      else 
+        echo " no state file found will create"
       fi
   artifacts:
     paths:
